### PR TITLE
Add dials for NBEATS

### PR DESCRIPTION
**Pull request by flrs**
This pull request adds a number of dials for the NBEATS algorithm and is in response to #14.

The default parameter ranges have roughly been chosen in accordance with the [GluonTS documentation](https://ts.gluon.ai/api/gluonts/gluonts.model.n_beats.html). It would be great if, before merging, someone with deeper expertise in NBEATS could confirm and/or modify those choices. Also note that no parameter has any transformation added. Should transformation be helpful in the context of a specific parameter, please feel free to comment.

### CODE REVIEW

**Comment by mdancho84** [comment]
Hey Florian, I appreciate the help on this. Give me through the weekend to review and get back to you with any comments. 👍

**Comment by mdancho84** [comment]
Hey Florian, 
I've merged the request. One issue I'm seeing is that if we create a function `scale()` it overwrites `base::scale()`, which is not good if people have used that function in their analysis. To get around this, I'm going to change the function name from `scale` to `scale_values()`.
-Matt

**Comment by flrs** [comment]
That sounds like a great idea! Thanks for reviewing and merging, @mdancho84!

**Comment by mdancho84** [comment]
Should be updated now. Use the dev version to get the updates.

**Pull request merged**
